# Generated by Django 3.2.2 on 2021-05-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cell',
            new_name='Post',
        ),
    ]
