# Generated by Django 3.2.2 on 2021-05-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0002_rename_cell_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Cell',
        ),
    ]
