# Generated by Django 3.2.2 on 2021-05-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0003_rename_post_cell'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cell',
            new_name='CellImage',
        ),
    ]
