# Generated by Django 3.2.2 on 2021-05-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0004_rename_cell_cellimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellimage',
            name='pub_date',
        ),
    ]
