# Generated by Django 3.2.2 on 2021-05-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0005_remove_cellimage_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellimage',
            name='body',
        ),
    ]
